<!-- 
     Copyright 2006-2019 Vidyasagar Mundroy

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<!--
 --- Function: Displays help on data transfer source database. 
 -->
 
<HTML>

<HEAD>
<TITLE>Source Database Table Selection for Data Transfer</TITLE>
<LINK REL="shortcut icon" HREF="../wji_images/wjilogo32.ico">
</HEAD>

<BODY bgcolor="#ffffff">

<%@include file="he_title.jsp"%>

<HR>

<H2><U>Source Database Table Selection for Data Transfer</U></H2>

<P>
Use this screen to select tables for the data transfer and initiate the 
transfer from the selected tables to the tables of destination database. 
</P>

<P>You can also view details of columns and keys of each source table, 
view data present in the table and even execute any SQL statement against 
the source database.
</P>

<P>If your database system
supports schemas or owners, it lists tables available in your default 
schema or those owned by you. If you want to see tables owned by another owner(user) or 
schema, enter the the name of the owner or schema in the corresponding field and
click <INPUT TYPE=BUTTON VALUE="Go">.
</P>

<I>
<SPAN STYLE="COLOR:RED;">Note:- 
<OL TYPE=i>
<LI>You may not see any list of tables if the owner name or schema name 
in the field <B>Owner/Schema</B> does not belong to the current database! 
This may happen if you used another owner or schema of another database
in an earlier occasion. If this is the case, change owner/schema name 
to the right name and click the button <INPUT TYPE=BUTTON VALUE="Go">
</OL>
</SPAN>
</I>


<P><B>Source Table List</B> :</P>

<P> The list contains information about tables from the source database 
for the selected schema or owner. It has the following columns:</P>
<OL>
<LI><B>SNO</B>: Serial number given by wjISQL for each source table.
The number
is generated by the tool and not the underlying database system.
<LI><B>Table name</B>: Name of the source table from which you may transfer
data.
<LI><B>Rows</B>: Number of rows present in a table.
<LI><B>Transfer ?</B>: This column contains one check box and a check box
for each table. Tick mark the check box against the table to select the table
for its data transfer. If you want to select all tables, tick mark the check box
that is present in the column heading.
<LI><B>Delete ?</B>: This contains one check box and a check box
for each table. Tick mark the check box against the table to <B>delete rows</B> 
from the corresponding table in the destination database before transferring 
data from the
source table. If you want to select all tables for the deletion, tick mark 
the check box that is present in the column heading.
</OL>

<P>
<B>Actions</B> you can perform in this window are as follows:
</P>

<UL>
<LI><INPUT TYPE=BUTTON VALUE="Transfer">: Transfers data from the selected
tables from the source database to the corresponding tables in the
destination database.
<BR><BR>
<LI><INPUT TYPE=BUTTON VALUE="Refresh">: Refreshes table list from the
source database. 
<BR><BR>
<LI><INPUT TYPE=BUTTON VALUE="Help">: Displays the help you are seeing now.
<BR><BR>
<LI><INPUT TYPE=BUTTON VALUE="Go">: Displays list of tables for the specified
 <B>Owner/Schema</B>.
<BR><BR>
<LI><B><U><I>Table name</I></U></B>: Each table name can be clicked to 
display information about columns. Once the information is displayed, you
can view data present in the table, keys defined on the table, you can 
even drop the table and execute any SQL statement on the destination database.
</UL>

<HR>
<%@include file="../wji_common/cmn_copyright.jsp"%>


</BODY>
</HTML>
