-- Many tables are created to test table list scrolling position is not disturbed 
-- when select statements are executed.
-- 
CREATE TABLE tst_t1(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t2(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t3(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t4(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t5(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t6(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t7(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t8(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t9(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t10(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t11(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t12(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t13(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t14(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t15(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t16(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t17(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t18(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t19(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t20(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t21(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t22(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t23(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t24(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t25(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t26(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t27(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t28(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t29(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));
CREATE TABLE tst_t30(c1 INT NOT NULL PRIMARY KEY, c2 VARCHAR(20));